
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: wnstj1819~
      MYSQL_DATABASE: hamtteukka_db
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: redis2
    ports:
      - "6379:6379"

  spring-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-server
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"

