#spring.application.name=hamtteukka
spring:
  application:
    name: hamtteukka

  datasource:
    # MySql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create # 로컬 개발환경시
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB


#server:
#  port: ${SERVER_PORT}
#  ssl:
#    enabled: false

OPENVIDU_URL: ${OPENVIDU_URL}
OPENVIDU_SECRET: ${OPENVIDU_SECRET}

KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}

FRONT_URI: ${FRONT_URI}

JWT_SECRETKEY: ${JWT_SECRETKEY}

AI_URL: ${AI_URL}

S3_BUCKET_NAME: ${S3_BUCKET_NAME}
S3_BUCKET_URL: ${S3_BUCKET_URL}
REGION: ${REGION}
IAM_ACCESSKEY: ${IAM_ACCESSKEY}
IAM_SECRETKEY: ${IAM_SECRETKEY}

REDIS_HOST: ${REDIS_HOST}
REDIS_PORT: ${REDIS_PORT}

logging:
  level:
    org.hibernate.SQL: debug



